In [1]:
import pandas as pd

In [76]:
accident = pd.read_csv('ACCIDENT.csv')
damage = pd.read_csv('DAMAGE.csv') ##
acc_aux = pd.read_csv('ACC_AUX.csv')
cevent = pd.read_csv('CEVENT.csv')
maneuver = pd.read_csv('MANEUVER.csv') ##
factor = pd.read_csv('FACTOR.csv') ##
distract = pd.read_csv('DISTRACT.csv') ##
drimpair = pd.read_csv('DRIMPAIR.csv') ##
parkwork = pd.read_csv ('PARKWORK.csv') ##
pbtype = pd.read_csv ('PBTYPE.csv')
nmprior = pd.read_csv('NMPRIOR.csv') ##
nmimpair = pd.read_csv('NMIMPAIR.csv') ##
nmcrash = pd.read_csv('NMCRASH.csv') ##
per_aux = pd.read_csv('PER_AUX.csv')
person = pd.read_csv('PERSON.csv') ##
veh_aux = pd.read_csv('VEH_AUX.csv')
vevent = pd.read_csv('VEVENT.csv')##
vsoe = pd.read_csv('VSOE.csv')##
violatn = pd.read_csv('VIOLATN.csv') ##
vision = pd.read_csv('VISION.csv') ##
vehicle = pd.read_csv('VEHICLE.csv') ##
safetyeq = pd.read_csv('SAFETYEQ.csv') ##

first merge vehicle info

In [47]:
# vehicle level

# vehicle: This data file contains information describing the in-transport
# motor vehicles and the drivers of in-transport motor vehicle who are involved in the
# crash. There is one record per in-transport motor vehicle. Parked and working vehicle
# information is in the Parkwork data file

# parkwork: This data file contains information about parked and working
# vehicles that were involved in FARS crashes

# vindecode: This data file contains vehicle descriptors for all vehicles,
# mainly passenger vehicles, trucks and motorcycles, based on the vehicleâ€™s VIN which is
# decoded using the VINtelligence program. There is one record per vehicle.

In [48]:
# merge vehicle and parkwork by casenum
vehicle_info = pd.concat([vehicle,parkwork], axis = 0,sort = False, ignore_index = True)

# merge with damage 
# damage: This data file contains information about all of the areas on
# this vehicle that were damaged in the crash. There is one record per damaged area.
damage['MDAREAS'] = damage['MDAREAS'].astype(str)
damage = damage.groupby(['CASENUM','VEH_NO'])['MDAREAS'].apply(','.join).reset_index()
vehicle_info = vehicle_info.merge(damage, how = 'inner', on = ['CASENUM','VEH_NO'])

# merge with factor
# factor: This data filecontains information about vehiclecircumstanceswhich may have contributed to the crash.  There is at least one record per in-transport motor vehicle. Each factor is a separate record.  
# merge MFACTOR into the current dataset by veh_no & casenum
vehicle_info = vehicle_info.merge(factor[['CASENUM','VEH_NO','MFACTOR']], how = 'outer', on = ['CASENUM','VEH_NO'])

# merge with distract
# distract: This data file contains information about driver distractions.  There is at least one record per in-transport motor vehicle. Each distraction is a separate record. 
# merge MDRDSTRD into the current dataset by veh_no & casenum
vehicle_info = vehicle_info.merge(distract[['CASENUM','VEH_NO','MDRDSTRD']], how = 'outer', on = ['CASENUM','VEH_NO'])

# merge with maneuver
#  This data file contains information about actions taken by
# the driver to avoid something or someone in the road. There is at least one record per
# in-transport motor vehicle. Each maneuver is a separate record. 
# merge MDRMANAV into the current dataset by veh_no & casenum
vehicle_info = vehicle_info.merge(maneuver[['CASENUM','VEH_NO','MDRMANAV']], how = 'outer', on = ['CASENUM','VEH_NO'])

# merge with drimpair
vehicle_info = vehicle_info.merge(drimpair[['CASENUM','VEH_NO','DRIMPAIR']], how = 'outer', on = ['CASENUM','VEH_NO'])

# merge with violation
vehicle_info = vehicle_info.merge(violatn[['CASENUM','VEH_NO','MVIOLATN']], how = 'outer', on = ['CASENUM','VEH_NO'])

# merge with vision 
vehicle_info = vehicle_info.merge(vision[['CASENUM','VEH_NO','MVISOBSC']], how = 'outer', on = ['CASENUM','VEH_NO'])



vehicle_info = vehicle_info.sort_values(by = ['CASENUM'])

In [49]:
vehicle_info.head(50)

,CASENUM,VEH_NO,REGION,PSU,PJ,PSU_VAR,URBANICITY,STRATUM,VE_FORMS,NUMOCCS,...,PTRLR1VIN,PTRLR2VIN,PTRLR3VIN,MDAREAS,MFACTOR,MDRDSTRD,MDRMANAV,DRIMPAIR,MVIOLATN,MVISOBSC
0,201800381338,1,4,56,208,208,1,9,4.0,1.0,...,NaN,NaN,NaN,12,0,0,4,0,0,0
1,201800381338,2,4,56,208,208,1,9,4.0,1.0,...,NaN,NaN,NaN,"6,12",0,0,4,0,0,0
2,201800381338,3,4,56,208,208,1,9,4.0,1.0,...,NaN,NaN,NaN,"6,12",0,0,0,0,0,0
3,201800381338,4,4,56,208,208,1,9,4.0,1.0,...,NaN,NaN,NaN,6,0,0,0,0,0,0
4,201800381366,1,4,56,214,214,1,7,3.0,1.0,...,NaN,NaN,NaN,"1,2,10,11,12",0,0,98,0,0,0
5,201800381366,2,4,56,214,214,1,7,3.0,1.0,...,NaN,NaN,NaN,"1,2,4,5,6,12",0,0,98,0,0,0
6,201800381366,3,4,56,214,214,1,7,3.0,1.0,...,NaN,NaN,NaN,"6,7",0,0,98,0,0,0
7,201800381374,1,4,56,214,214,1,6,2.0,2.0,...,NaN,NaN,NaN,"3,4,5",0,0,92,0,0,0
8,201800381374,2,4,56,214,214,1,6,2.0,1.0,...,NaN,NaN,NaN,"7,8,9,10,11",0,0,92,0,0,0
10,201800383118,2,4,56,209,209,1,10,2.0,1.0,...,NaN,NaN,NaN,12,0,0,98,0,0,0
9,201800383118,1,4,56,209,209,1,10,2.0,99.0,...,NaN,NaN,NaN,"5,6",98,99,98,99,0,0
11,201800383942,1,4,64,306,64,1,6,2.0,1.0,...,NaN,NaN,NaN,"10,11",0,0,4,0,0,0
12,201800383942,2,4,64,306,64,1,6,2.0,2.0,...,NaN,NaN,NaN,"5,6",0,0,98,0,0,0
13,201800383966,1,4,56,189,189,1,10,2.0,1.0,...,NaN,NaN,NaN,"8,9,10",0,0,98,0,0,0
14,201800383966,2,4,56,189,189,1,10,2.0,2.0,...,NaN,NaN,NaN,"4,5",0,0,98,0,0,0
15,201800384289,1,4,68,295,68,1,6,2.0,1.0,...,NaN,NaN,NaN,"1,2,3,4,11,12",0,0,98,9,11,0
16,201800384289,2,4,68,295,68,1,6,2.0,3.0,...,NaN,NaN,NaN,"1,2,3,4,5,6,13,14,7,8,9,10,11,12",0,0,98,0,0,0
17,201800384377,1,3,48,91,48,1,9,1.0,99.0,...,NaN,NaN,NaN,12,3,99,98,99,0,0
18,201800384395,1,3,48,85,48,1,10,1.0,1.0,...,NaN,NaN,NaN,"1,11,12",0,14,3,0,0,0
20,201800384410,2,3,48,91,48,1,10,2.0,1.0,...,NaN,NaN,NaN,6,0,0,0,0,0,0
19,201800384410,1,3,48,91,48,1,10,2.0,2.0,...,NaN,NaN,NaN,12,0,0,98,0,0,0
22,201800384413,2,3,48,91,48,1,8,2.0,1.0,...,NaN,NaN,NaN,6,0,0,0,0,0,0
21,201800384413,1,3,48,91,48,1,8,2.0,1.0,...,NaN,NaN,NaN,"1,11,12",0,0,98,0,0,0
23,201800384428,1,3,48,87,48,1,10,2.0,1.0,...,NaN,NaN,NaN,"1,11,12",0,0,98,0,0,0
24,201800384428,2,3,48,87,48,1,10,2.0,1.0,...,NaN,NaN,NaN,"1,11,12",0,0,98,0,0,0
25,201800384440,1,3,48,87,48,1,9,3.0,2.0,...,NaN,NaN,NaN,12,0,92,98,0,71,0
26,201800384440,2,3,48,87,48,1,9,3.0,2.0,...,NaN,NaN,NaN,"6,12",0,0,0,0,0,0
27,201800384440,3,3,48,87,48,1,9,3.0,1.0,...,NaN,NaN,NaN,6,0,0,0,0,0,0
28,201800384450,1,3,48,87,48,1,6,2.0,1.0,...,NaN,NaN,NaN,"11,12",0,0,98,0,72,0
29,201800384450,2,3,48,87,48,1,6,2.0,2.0,...,NaN,NaN,NaN,"1,12",0,0,98,0,0,0
30,201800384454,1,3,48,87,48,1,8,2.0,1.0,...,NaN,NaN,NaN,"8,9",0,0,98,0,0,0
31,201800384454,2,3,48,87,48,1,8,2.0,1.0,...,NaN,NaN,NaN,12,0,0,98,0,0,0
33,201800384467,2,3,48,87,48,1,10,2.0,1.0,...,NaN,NaN,NaN,6,0,0,98,0,0,0
32,201800384467,1,3,48,87,48,1,10,2.0,1.0,...,NaN,NaN,NaN,12,0,0,98,0,0,0
34,201800384468,1,3,48,87,48,1,9,2.0,1.0,...,NaN,NaN,NaN,"1,12",0,0,98,0,0,0
35,201800384468,2,3,48,87,48,1,9,2.0,1.0,...,NaN,NaN,NaN,"5,6",0,0,98,0,0,0
36,201800384476,1,3,48,87,48,1,7,2.0,1.0,...,NaN,NaN,NaN,15,0,0,98,0,0,0
37,201800384476,2,3,48,87,48,1,7,2.0,1.0,...,NaN,NaN,NaN,"1,2",0,0,98,0,0,0
38,201800384504,1,3,48,87,48,1,10,1.0,1.0,...,NaN,NaN,NaN,"12,14",0,0,3,0,0,0
39,201800384508,1,3,48,87,48,1,9,2.0,1.0,...,NaN,NaN,NaN,1,0,0,98,0,0,0
40,201800384508,2,3,48,87,48,1,9,2.0,1.0,...,NaN,NaN,NaN,"8,9,10",0,0,98,0,0,0
42,201800384517,2,3,48,87,48,1,5,2.0,4.0,...,NaN,NaN,NaN,"11,12",0,0,98,0,75,0
41,201800384517,1,3,48,87,48,1,5,2.0,1.0,...,NaN,NaN,NaN,12,0,0,98,99,0,0
44,201800384543,2,3,48,87,48,1,10,2.0,1.0,...,NaN,NaN,NaN,"6,7",0,0,0,0,0,0
43,201800384543,1,3,48,87,48,1,10,2.0,1.0,...,NaN,NaN,NaN,"1,12",0,0,98,0,0,0
45,201800384545,1,3,48,87,48,1,6,5.0,2.0,...,NaN,NaN,NaN,12,0,0,98,0,0,0
46,201800384545,2,3,48,87,48,1,6,5.0,2.0,...,NaN,NaN,NaN,"6,12",0,0,0,0,0,0
47,201800384545,3,3,48,87,48,1,6,5.0,2.0,...,NaN,NaN,NaN,"6,12",0,0,0,0,0,0
48,201800384545,4,3,48,87,48,1,6,5.0,1.0,...,NaN,NaN,NaN,6,0,0,0,0,0,0
49,201800384545,5,3,48,87,48,1,6,5.0,1.0,...,NaN,NaN,NaN,6,0,0,0,0,75,0

In [50]:
vehicle_info.to_csv('vehicle_info.csv')

merge person info

In [65]:
# person: This data file contains information describing all persons involved in the crash including motorists 
# pbtype: This data file contains information about crashes between
# motor vehicles and pedestrians, people on personal conveyances and bicyclists
# safetype: This data file contains information about safety equipment
# used by people who are not occupants of motor vehicles. T

# merge person and pbtype
person_info = pd.concat([person, pbtype], axis = 0,sort = False, ignore_index = True)

# merge safetype
person_info = person_info.merge(safetyeq[['CASENUM','VEH_NO','PER_NO', 'NMHELMET',
                                         'NMPROPAD','NMOTHPRO','NMREFCLO','NMLIGHT','NMOTHPRE']], how = 'outer', on = ['CASENUM','VEH_NO','PER_NO'])

# merge drugs???

# merge nmcrash
person_info = person_info.merge(nmcrash[['CASENUM','VEH_NO','PER_NO', 'MTM_CRSH']], how = 'outer', on = ['CASENUM','VEH_NO','PER_NO'])

# merge nmimpair
person_info = person_info.merge(nmimpair[['CASENUM','VEH_NO','PER_NO','NMIMPAIR']], how = 'outer', on = ['CASENUM','VEH_NO','PER_NO'])

# merge nmprior
person_info = person_info.merge(nmprior[['CASENUM','VEH_NO','PER_NO','MPR_ACT']], how = 'outer', on = ['CASENUM','VEH_NO','PER_NO'])


person_info = person_info.sort_values(by = ['CASENUM'])

In [66]:
person_info.tail(50)
person_info.to_csv('person_info.csv')

merge crash & event info

In [78]:
# cevent: This data file contains information for all of the qualifying
# events (i.e., both harmful and non-harmful involving in-transport motor vehicles) which
# occurred in the crash

# vevent:This data file contains the sequence of events for each intransport motor vehicle involved in the crash. 

# vsoe: This data file contains the sequence of events for each intransport motor vehicle involved in the crash. 

# merge event and accident
accident_info = accident.merge(vevent, how = 'outer', on = 'CASENUM',suffixes=('', '_y'))
accident_info = accident_info.drop(accident_info.filter(regex='_y$').columns.tolist(),axis=1)

accident_info.head()

,CASENUM,REGION,PSU,PJ,PSU_VAR,URBANICITY,STRATUM,VE_TOTAL,VE_FORMS,PVH_INVL,...,PSUSTRAT,WEIGHT,EVENTNUM,VEH_NO,VEVENTNUM,VNUMBER1,AOI1,SOE,VNUMBER2,AOI2
0,201800381338,4,56,208,208,1,9,4,4,0,...,20,187.193308,1,1,1,1,12,12,2,6
1,201800381338,4,56,208,208,1,9,4,4,0,...,20,187.193308,1,2,1,1,12,12,2,6
2,201800381338,4,56,208,208,1,9,4,4,0,...,20,187.193308,2,2,2,2,12,12,3,6
3,201800381338,4,56,208,208,1,9,4,4,0,...,20,187.193308,2,3,1,2,12,12,3,6
4,201800381338,4,56,208,208,1,9,4,4,0,...,20,187.193308,3,3,2,3,12,12,4,6

In [ ]:
accident_info.to_csv('accident_info.csv')

In [74]:
# merge three data files
full_data = accident_info.merge(person_info, how = 'outer', on = ['CASENUM','VEH_NO'], suffixes=('', '_y'))
full_data = full_data.drop(full_data.filter(regex='_y$').columns.tolist(),axis=1, inplace=True)

full_data = full_data.merge(vehicle_info, how = 'outer', on = ['CASENUM','VEH_NO'],suffixes=('', '_y'))
full_data = full_data.drop(full_data.filter(regex='_y$').columns.tolist(),axis=1, inplace=True)

full_data.to_csv('full_data.csv')